hydra:
    run:
        dir: ./results/train-pipeline/${backbone}/${now:%Y-%m-%d}/${now:%H-%M-%S}
batch_size: 64
epochs: 100
lr: 0.01
device: 'cuda:0'
workers: 2
weights: ./weights
logs: ./logs
voc12_root: ${hydra:runtime.cwd}/../vision/data/raw/VOCdevkit/VOC2012
train_list: ${hydra:runtime.cwd}/voc12/train.txt
val_list: ${hydra:runtime.cwd}/voc12/val.txt
cls_label_path: ${hydra:runtime.cwd}/voc12/cls_labels.npy
crop_size: 320
weight_decay: 1e-4
out_ch: 21
num_classes: 20
backbone: resnet50v2
temp_dir: ${hydra:runtime.cwd}/results/temp_dir/${now:%Y-%m-%d}/${now:%H-%M-%S}
in_channels: 2048
dilate_version: 1
patience: 5
